/**
 * Datos de ejemplo portados del prototipo Fincas.dc.html. Se cargan una sola
 * vez, cuando el store está vacío (ver repos.js).
 */
export const SEED = {
  config: { guestCount: 140, defaultView: 'rejilla', theme: 'light', lang: 'es' },
  presupuesto: { limite: 45000, partidas: [] },
  categorias: ['Wedding planner', 'Fotografía', 'Vídeo', 'Flores', 'Decoración', 'Catering',
    'Grupo de música', 'DJ', 'Saxofonista', 'Actuaciones y shows', 'Fotomatón', 'Tarta',
    'Peluquería y maquillaje', 'Invitaciones y papelería', 'Coche de novios', 'Autobuses',
    'Barra y cócteles', 'Animación infantil', 'Fuegos artificiales'],
  mesas: [
    { id: 'm1', nombre: 'Presidencial', capacidad: 10, forma: 'rectangular', x: 50, y: 20 },
    { id: 'm2', nombre: 'Mesa 2', capacidad: 10, forma: 'redonda', x: 26, y: 48 },
    { id: 'm3', nombre: 'Mesa 3', capacidad: 10, forma: 'redonda', x: 50, y: 62 },
    { id: 'm4', nombre: 'Mesa 4', capacidad: 8, forma: 'redonda', x: 74, y: 48 },
  ],

  fincas: [
    {
      id: '9', nombre: 'La Quinta de Jarama', tipo: 'Finca', zona: 'San Sebastián de los Reyes, Madrid', km: 26, capSent: 900, capPie: 900, menu: 160, alquiler: 0, valoracion: 4.8, estado: 'favorita',
      servicios: ['Ceremonia civil', 'Jardines y estanques', 'Terraza', 'Zona de baile', 'Parking', 'Cocina propia', 'Sin límite de hora', 'Un solo evento al día'],
      fechas: ['Viernes 2026 desde 160 €', 'Diciembre desde 160 €'],
      notas: 'Premio Nacional de Hostelería 2010. Interiores de Pascua Ortega renovados por Estudio Singular. Exclusividad de catering: la gastronomía es suya. Alquiler variable según fecha y nº de invitados; señal al reservar y resto una semana antes. Sin alojamiento para invitados. 4,8/5 con 246 opiniones en Bodas.net.',
      motivo: '',
      fotos: [
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/png/la-escalera-del-torreon-de-la-quinta-de-jarama_1_2565-170084598333441.jpeg', pie: 'La escalera del torreón' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-mesas-para-mas-de-400-invitados_1_2565-170084360973603.jpeg', pie: 'Montaje para más de 400 invitados' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/montaje-mesas-olivos-agua-aire-libre-exterior_1_2565-170084361037231.jpeg', pie: 'Banquete al aire libre' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/img-6201_1_2565-170084360520803.jpeg', pie: 'Ceremonia al aire libre' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpeg/la-quinta-de-jarama-y-sus-estanques_1_2565-170084360615388.jpeg', pie: 'Los estanques' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-y-sus-jardines_1_2565-170084360985785.jpeg', pie: 'Jardines y fuentes' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/png/la-quinta-de-jarama-a-entrada-nocturna_1_2565-170084360378771.jpeg', pie: 'La entrada de noche' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/thelivingromm2-laquintadejarama-2_1_2565-1564553529.jpeg', pie: 'Espacio The Living Room' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-cenas-al-aire-libre_1_2565-170084360593494.jpeg', pie: 'Cenas en el exterior' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-gastronomia_1_2565-170084360484012.jpeg', pie: 'Gastronomía: tartar de atún' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/ceremonia-civil-casa-de-los-tilos-dsc02146_1_2565-170084349670065.jpeg', pie: 'Pasillo de la ceremonia' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/montaje-con-mesa-rectangular-imperial-olivos-agua-centros-primavera_1_2565-170084360680531.jpeg', pie: 'Mesa imperial en el comedor' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/-mg-0001_1_2565.jpeg', pie: 'Entrada' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpeg/la-quinta-de-jarama-presentaciones_1_2565-170084360520302.jpeg', pie: 'Corner de limonadas' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/img-6197_1_2565-170084360579779.jpeg', pie: 'Ceremonia civil' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/20111115080012311_1_2565.jpeg', pie: 'La finca iluminada' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-entrada_1_2565-170084360545635.jpeg', pie: 'Escaleras de la quinta' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-gastronomia-craquelin_1_2565-170084360860912.jpeg', pie: 'Craquelín' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/craquelin_1_2565.jpeg', pie: 'Craquelín de la cocina' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/-dsc5127_1_2565.jpeg', pie: 'Merluza al horno con patatitas' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/fresas_1_2565.jpeg', pie: 'Postre de fresas' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/videoshowlaquintadejarama03_1_2565.jpeg', pie: 'La Quinta de Jarama' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/0309-ana-y-yago_1_2565-170507401018749.jpeg', pie: 'Estación de quesos móvil' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/videoshowlaquintadejarama10_1_2565.jpeg', pie: 'Salón de banquetes' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/videoshowlaquintadejarama13_1_2565.jpeg', pie: 'Zona de fiesta' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/thelivingromm8-laquintadejarama-2_1_2565-1564553509.jpeg', pie: 'The Living Room' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/20230624-boda-jarama-68_1_2565-170507394643428.jpeg', pie: 'Escaleras en una boda' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/png/centro-de-mesa-navidad-2022-30_1_2565-170507398036850.jpeg', pie: 'Centro de mesa' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/png/la-quinta-de-jarama_1_2565-170507403984373.jpeg', pie: 'Comedor' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-casa-de-los-tilos-1_1_2565-170507424016775.jpeg', pie: 'Acceso a la Casa de los Tilos' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/jardines-de-la-quinta-de-jarama-para-hacer-montaje-al-aire-libre_1_2565-173644663482788.jpeg', pie: 'Jardines para cenas' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/montaje-en-los-porches_1_2565-173644665388043.jpeg', pie: 'Montajes en los porches' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/cena-al-aire-libre-en-los-jardines-en-julio_1_2565-173644668385044.jpeg', pie: 'Cena al aire libre en julio' },
        { url: 'https://cdn0.bodas.net/vendor/2565/3_2/960/jpg/la-quinta-de-jarama-jardines-para-el-cocktail_1_2565-173644669952330.jpeg', pie: 'Jardines para el cóctel' },
      ],
      tour: { poster: 'https://cdn0.bodas.net/tour3d/8413/3_2/960/jpg/8413_2565_2025-06-25-17-35-16.jpeg', url: 'https://www.bodas.net/fincas/la-quinta-de-jarama--e2565#gallery', label: 'Tour 360º · 2 recorridos' },
    },
    { id: '1', nombre: 'Finca Valdetrigos', tipo: 'Finca', zona: 'Guadarrama, Madrid', km: 52, capSent: 300, capPie: 500, menu: 118, alquiler: 0, valoracion: 4.6, estado: 'favorita', servicios: ['Ceremonia civil', 'Jardín cubierto', 'Parking', 'Barra libre 04:00'], fechas: ['12 jun', '26 jun', '11 sep'], notas: 'La chopera para el cóctel es el mejor espacio que hemos visto. Obligan a su catering.', motivo: '' },
    { id: '2', nombre: 'Hacienda El Torreón', tipo: 'Hacienda', zona: 'Aranjuez, Madrid', km: 48, capSent: 220, capPie: 350, menu: 135, alquiler: 0, valoracion: 4.8, estado: 'favorita', servicios: ['Ceremonia civil', 'Alojamiento 18 hab.', 'Piscina', 'Barra libre 05:00'], fechas: ['5 jun', '19 jun', '3 jul'], notas: 'Coordinadora impecable. Caben justo los 140 en el patio si llueve.', motivo: '' },
    { id: '3', nombre: 'Masía Can Ribes', tipo: 'Masía', zona: 'Sant Cugat, Barcelona', km: 610, capSent: 180, capPie: 260, menu: 148, alquiler: 0, valoracion: 4.4, estado: 'candidata', servicios: ['Ceremonia civil', 'Catering propio', 'Bodega visitable'], fechas: ['26 jun', '10 jul'], notas: 'Preciosa, pero la mitad de los invitados tendría que volar.', motivo: '' },
    { id: '4', nombre: 'Bodega Viña Sanchís', tipo: 'Bodega', zona: 'Valdepeñas, C. Real', km: 195, capSent: 160, capPie: 240, menu: 92, alquiler: 4800, valoracion: 4.2, estado: 'candidata', servicios: ['Catering libre', 'Visita a la nave', 'Parking'], fechas: ['19 jun', '4 sep', '18 sep'], notas: 'Alquiler aparte pero dejan traer a nuestro catering y barra.', motivo: '' },
    { id: '5', nombre: 'Castillo de Peñalba', tipo: 'Castillo', zona: 'El Barraco, Ávila', km: 118, capSent: 250, capPie: 400, menu: 96, alquiler: 9500, valoracion: 4.9, estado: 'candidata', servicios: ['Ceremonia civil', 'Alojamiento 22 hab.', 'Patio de armas', 'Exclusividad 24 h'], fechas: ['29 may', '12 jun'], notas: 'Espectacular. Se come casi todo el presupuesto de decoración.', motivo: '' },
    { id: '6', nombre: 'El Molino de la Vega', tipo: 'Casa rural', zona: 'Rascafría, Madrid', km: 78, capSent: 120, capPie: 180, menu: 88, alquiler: 1200, valoracion: 4.1, estado: 'descartada', servicios: ['Alojamiento 9 hab.', 'Río', 'Catering libre'], fechas: ['6 jun', '20 jun'], notas: 'Encantador pero no entran 140 sentados.', motivo: 'Aforo insuficiente' },
    { id: '7', nombre: 'Palacete Los Almendros', tipo: 'Espacio singular', zona: 'Toledo', km: 86, capSent: 170, capPie: 250, menu: 125, alquiler: 0, valoracion: 4.5, estado: 'candidata', servicios: ['Ceremonia civil', 'Claustro cubierto', 'Barra libre 03:00'], fechas: ['13 jun', '27 jun', '12 sep'], notas: 'Muy buena relación calidad-precio. Cierran música a las 03:00.', motivo: '' },
    { id: '8', nombre: 'Cortijo La Herradura', tipo: 'Finca', zona: 'Colmenar Viejo, Madrid', km: 34, capSent: 260, capPie: 420, menu: 105, alquiler: 0, valoracion: 3.9, estado: 'candidata', servicios: ['Ceremonia civil', 'Parking 120 plazas', 'Carpa'], fechas: ['5 jun', '19 jun', '25 sep'], notas: 'La más cerca y la más barata; el salón interior es frío.', motivo: '' },
  ],

  invitados: [
    { id: 'g01', nombre: 'Carmen Ibáñez Ruiz', lado: 'novia', grupo: 'Familia directa', rsvp: 'confirmado', plus: 1, nota: 'Madre de la novia', invitacion: 'respondida', menu: 'Estándar', acompanantes: ['Javier Soler'], mesa: 'm1' },
    { id: 'g02', nombre: 'Luis Ibáñez Soler', lado: 'novia', grupo: 'Familia directa', rsvp: 'confirmado', plus: 0, nota: 'Padre de la novia', invitacion: 'respondida', menu: 'Estándar', acompanantes: [], mesa: 'm1' },
    { id: 'g03', nombre: 'Marta Ibáñez', lado: 'novia', grupo: 'Familia directa', rsvp: 'confirmado', plus: 1, nota: 'Hermana · dama de honor', invitacion: 'respondida', menu: 'Estándar', acompanantes: [], mesa: 'm1' },
    { id: 'g04', nombre: 'Tía Pilar y tío Nacho', lado: 'novia', grupo: 'Familia extensa', rsvp: 'pendiente', plus: 0, nota: '', invitacion: 'enviada', menu: 'Estándar', acompanantes: [] },
    { id: 'g05', nombre: 'Nuria Beltrán', lado: 'novia', grupo: 'Amigos de siempre', rsvp: 'confirmado', plus: 1, nota: 'Sin gluten', invitacion: 'respondida', menu: 'Celíaco', acompanantes: ['Pablo Arias'], mesa: 'm2' },
    { id: 'g06', nombre: 'Sara Caballero', lado: 'novia', grupo: 'Amigos de siempre', rsvp: 'pendiente', plus: 1, nota: '', invitacion: 'enviada', menu: 'Estándar', acompanantes: [] },
    { id: 'g07', nombre: 'Elena Prats', lado: 'novia', grupo: 'Amigos del trabajo', rsvp: 'pendiente', plus: 0, nota: '', invitacion: 'recordatorio', menu: 'Vegetariano', acompanantes: [] },
    { id: 'g08', nombre: 'Rosa Villar', lado: 'novio', grupo: 'Familia directa', rsvp: 'confirmado', plus: 0, nota: 'Madre del novio', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g09', nombre: 'Antonio Gutiérrez', lado: 'novio', grupo: 'Familia directa', rsvp: 'confirmado', plus: 0, nota: 'Padre del novio', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g10', nombre: 'Javier Gutiérrez', lado: 'novio', grupo: 'Familia directa', rsvp: 'confirmado', plus: 1, nota: 'Hermano · padrino', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g11', nombre: 'Primos de Lugo', lado: 'novio', grupo: 'Familia extensa', rsvp: 'pendiente', plus: 3, nota: 'Cuatro personas', invitacion: 'recordatorio', menu: 'Estándar', acompanantes: ['Marcos', 'Iria', 'Brais'] },
    { id: 'g12', nombre: 'Álex Ferrer', lado: 'novio', grupo: 'Amigos de siempre', rsvp: 'confirmado', plus: 1, nota: '', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g13', nombre: 'Dani Ochoa', lado: 'novio', grupo: 'Amigos de siempre', rsvp: 'confirmado', plus: 0, nota: 'Viene desde Bilbao', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g14', nombre: 'Equipo de oficina', lado: 'novio', grupo: 'Amigos del trabajo', rsvp: 'no', plus: 0, nota: 'Solo al cóctel', invitacion: 'respondida', menu: 'Estándar', acompanantes: [] },
    { id: 'g15', nombre: 'Abuela Trini', lado: 'novio', grupo: 'Familia extensa', rsvp: 'confirmado', plus: 1, nota: 'Mesa cerca de la puerta', invitacion: 'respondida', menu: 'Sin sal', acompanantes: ['Rocío (cuidadora)'] },
  ],

  proveedores: [
    { id: 'p01', nombre: 'Estudio Ala Wedding', categoria: 'Wedding planner', estado: 'contratado', precio: 3200, senal: 900, contacto: 'Bea', telefono: '600 112 233', notas: 'Coordinación integral + día D. Incluye dos visitas a la finca.', fechaPago: '2026-11-15', checklist: { presupuesto: true, senal: true, contrato: true, confirmado: false } },
    { id: 'p02', nombre: 'Carla Nieto Fotografía', categoria: 'Fotografía', estado: 'contratado', precio: 2400, senal: 600, contacto: 'Carla', telefono: 'hola@carlanieto.es', notas: 'Reportaje 12 h, dos cámaras, álbum y galería online.', fechaPago: '2027-01-10', checklist: { presupuesto: true, senal: true, contrato: true, confirmado: false } },
    { id: 'p03', nombre: 'Sextante Films', categoria: 'Vídeo', estado: 'presupuesto', precio: 1950, senal: 0, contacto: 'Rubén', telefono: '611 445 221', notas: 'Vídeo resumen 6 min + ceremonia completa. Pendiente confirmar dron.' },
    { id: 'p04', nombre: 'Flores Marbella Norte', categoria: 'Flores', estado: 'presupuesto', precio: 1650, senal: 0, contacto: 'Lidia', telefono: '629 887 004', notas: 'Ramo, centros de mesa y arco de ceremonia con olivo y eucalipto.' },
    { id: 'p05', nombre: 'Taller Nudo', categoria: 'Decoración', estado: 'contactado', precio: 1200, senal: 0, contacto: 'Nacho', telefono: 'taller@nudo.es', notas: 'Seating plan, velas y textiles. Pedir muestras.' },
    { id: 'p06', nombre: 'La Quinta de Jarama (cocina propia)', categoria: 'Catering', estado: 'contratado', precio: 22400, senal: 4000, contacto: 'Mónica', telefono: '916 540 000', notas: 'Exclusividad de catering de la finca. 160 €/invitado + IVA.', fechaPago: '2027-03-01', checklist: { presupuesto: true, senal: true, contrato: true, confirmado: true } },
    { id: 'p07', nombre: 'Cuarteto Alameda', categoria: 'Grupo de música', estado: 'presupuesto', precio: 1400, senal: 0, contacto: 'Elena', telefono: '655 230 118', notas: 'Cuarteto de cuerda para ceremonia y cóctel (90 min).' },
    { id: 'p08', nombre: 'DJ Ferrán Sala', categoria: 'DJ', estado: 'contratado', precio: 1100, senal: 300, contacto: 'Ferrán', telefono: 'dj@ferransala.com', notas: 'Barra libre sin límite de hora, incluye iluminación robotizada.', fechaPago: '2026-10-30', checklist: { presupuesto: true, senal: true, contrato: false, confirmado: false } },
    { id: 'p09', nombre: 'Saxo Lisboa', categoria: 'Saxofonista', estado: 'contactado', precio: 650, senal: 0, contacto: 'Tiago', telefono: '644 009 771', notas: 'Saxo en directo sobre la sesión del DJ, 45 min de entrada a pista.' },
    { id: 'p10', nombre: 'Compañía Vaivén', categoria: 'Actuaciones y shows', estado: 'pendiente', precio: 0, senal: 0, contacto: '', telefono: '', notas: 'Idea: show de flamenco fusión antes de la recena. Pedir vídeo.' },
    { id: 'p11', nombre: 'Cabina Lumière', categoria: 'Fotomatón', estado: 'presupuesto', precio: 720, senal: 0, contacto: 'Ana', telefono: '622 341 909', notas: 'Cabina vintage 4 h con libro de firmas e impresión ilimitada.' },
    { id: 'p12', nombre: 'Obrador Malvar', categoria: 'Tarta', estado: 'contactado', precio: 480, senal: 0, contacto: 'Rosa', telefono: 'pedidos@malvar.es', notas: 'Uno de los cuatro obradores autorizados por la finca.' },
    { id: 'p13', nombre: 'Estudio Bruma', categoria: 'Peluquería y maquillaje', estado: 'presupuesto', precio: 540, senal: 0, contacto: 'Sandra', telefono: '677 556 231', notas: 'Prueba incluida, dos personas a domicilio la mañana de la boda.' },
    { id: 'p14', nombre: 'Autocares Jarama', categoria: 'Autobuses', estado: 'pendiente', precio: 0, senal: 0, contacto: '', telefono: '', notas: 'Dos autobuses Madrid–finca ida y vuelta, incluida la vuelta de madrugada.' },
  ],

  // Guion del día (Timing): momentos ordenados con hora, duración, bloque, lugar y responsable.
  timing: [
    { id: 't01', orden: 1, bloque: 'preparativos', titulo: 'Peinado y maquillaje', inicio: '10:00', dur: 150, lugar: 'Suite nupcial', prov: 'p13', nota: 'Dos personas a domicilio; prueba ya hecha.' },
    { id: 't02', orden: 2, bloque: 'preparativos', titulo: 'Recepción de invitados', inicio: '12:30', dur: 30, lugar: 'Jardín de acceso', prov: '', nota: 'Agua aromatizada y sombra a la llegada.' },
    { id: 't03', orden: 3, bloque: 'ceremonia', titulo: 'Ceremonia civil', inicio: '13:00', dur: 40, lugar: 'La chopera', prov: 'p07', nota: 'Cuarteto de cuerda en la entrada y las firmas.' },
    { id: 't04', orden: 4, bloque: 'ceremonia', titulo: 'Felicitaciones y foto de grupo', inicio: '13:40', dur: 35, lugar: 'Jardín', prov: 'p02', nota: 'Foto general con dron antes del cóctel.' },
    { id: 't05', orden: 5, bloque: 'celebracion', titulo: 'Cóctel de bienvenida', inicio: '14:15', dur: 90, lugar: 'Terraza', prov: 'p06', nota: 'Saxo en directo la primera media hora.' },
    { id: 't06', orden: 6, bloque: 'celebracion', titulo: 'Banquete', inicio: '15:45', dur: 135, lugar: 'Salón principal', prov: 'p06', nota: 'Tres tiempos + brindis de los padrinos.' },
    { id: 't07', orden: 7, bloque: 'fiesta', titulo: 'Primer baile', inicio: '18:00', dur: 15, lugar: 'Pista', prov: 'p08', nota: 'Entrada de los novios con saxo.' },
    { id: 't08', orden: 8, bloque: 'fiesta', titulo: 'Apertura de barra libre', inicio: '18:15', dur: 45, lugar: 'Pista y barra', prov: 'p08', nota: 'Iluminación robotizada desde aquí.' },
    { id: 't09', orden: 9, bloque: 'fiesta', titulo: 'Fotomatón', inicio: '19:00', dur: 180, lugar: 'Zona chill', prov: 'p11', nota: 'Cabina vintage con libro de firmas.' },
    { id: 't10', orden: 10, bloque: 'fiesta', titulo: 'Recena', inicio: '22:00', dur: 45, lugar: 'Barra', prov: 'p06', nota: 'Mini hamburguesas y jamón.' },
    { id: 't11', orden: 11, bloque: 'fiesta', titulo: 'Show sorpresa', inicio: '22:45', dur: 20, lugar: 'Pista', prov: 'p10', nota: 'Flamenco fusión antes de volver a la pista.' },
    { id: 't12', orden: 12, bloque: 'fiesta', titulo: 'Fiesta y DJ', inicio: '23:20', dur: 180, lugar: 'Pista', prov: 'p08', nota: 'Sesión sin límite de hora.' },
    { id: 't13', orden: 13, bloque: 'fiesta', titulo: 'Autobuses de vuelta', inicio: '02:30', dur: 30, lugar: 'Entrada', prov: 'p14', nota: 'Dos turnos Madrid; recogida en la puerta.' },
  ],
};
